import Head from "next/head";
import Sidebar from "../components/Sidebar";
import logo from "../assets/whatsapp.svg";
import Image from "next/image";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
    </div>
  );
};
export default Home;
